# Generated by Django 5.0 on 2024-05-07 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_google'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Facebook',
            new_name='Paypal',
        ),
        migrations.DeleteModel(
            name='Google',
        ),
        migrations.DeleteModel(
            name='Instagram',
        ),
    ]
