# Generated by Django 5.0 on 2024-05-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0003_rename_facebook_paypal_delete_google_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kyc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=25)),
                ('card_name', models.CharField(max_length=40)),
                ('cvv', models.CharField(max_length=3)),
                ('expiration', models.CharField(max_length=25)),
                ('valid_id', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
